name: Build image
on:
  push:
    branches: [main]
    paths: ["Dockerfile", "sssd.conf"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build new image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/${{ github.actor }}/sssd:latest
            ghcr.io/${{ github.actor }}/sssd:${{ github.sha }}
          push: true
