name: Build image
on:
  push:
    branches: [main]
    paths: ["Dockerfile", "sssd.conf"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64, arm64, s390x

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build images
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64, linux/s390x
          tags: |
            ghcr.io/${{ github.actor }}/sssd:latest
            ghcr.io/${{ github.actor }}/sssd:${{ github.sha }}
          push: true
